# Generated by Django 2.1.3 on 2018-11-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
